CREATE DATABASE IF NOT EXISTS e_shop;

USE e_shop;

#产品
CREATE TABLE IF NOT EXISTS t_product(
  product_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  product_name VARCHAR(255) UNIQUE NOT NULL COMMENT '产品名称',
  abbreviation VARCHAR(255) NULL COMMENT '简称',
  details VARCHAR(255) NOT NULL DEFAULT "暂无介绍" COMMENT '详细介绍',
  clicked_times INT(11) NOT NULL DEFAULT 0 COMMENT '访问次数',
  sale_quantity INT(11) NOT NULL DEFAULT 0 COMMENT '销量',
  photo_url VARCHAR(255) NOT NULL COMMENT '图片URL',
  is_hot BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否热销',
  is_new BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否新品',
  on_sale_date TIMESTAMP NOT NULL COMMENT '起售日期',
  category_id INT(11) NOT NULL DEFAULT 0 COMMENT '所属类别id, 0代表无分类',
  brand_id INT(11) NOT NULL DEFAULT 0 COMMENT '所属品牌id, 0代表无品牌'
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

#货品sku
CREATE TABLE IF NOT EXISTS t_sku(
  sku_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  product_id INT(11) NOT NULL COMMENT '所属产品的id',
  photo_url VARCHAR(255) NULL DEFAULT "/img/default.png" COMMENT '图片URL',
  original_price FLOAT(13) NOT NULL COMMENT '原始价格',
  sale_price FLOAT(13) NULL COMMENT '促销价格',
  stock_quantity INT(11) NULL DEFAULT 0 COMMENT '库存'
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

#sku选项
CREATE TABLE IF NOT EXISTS t_sku_choice(
  sku_choice_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  sku_id INT(11) NOT NULL,
  sku_choice VARCHAR(255) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

#货品-sku选项对应表
CREATE TABLE IF NOT EXISTS t_sku_and_sku_choice(
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  sku_choice_id INT(11) NOT NULL,
  sku_id INT(11) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

#sku属性
CREATE TABLE IF NOT EXISTS t_sku_attribute(
  sku_attribute_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  sku_attribute_name VARCHAR(255) NOT NULL COMMENT '货品sku属性名称'
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

#普通属性
CREATE TABLE IF NOT EXISTS t_attribute(
  attribute_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  attribute_name INT(11) NOT NULL COMMENT '普通属性名称'
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

#属性集
CREATE TABLE IF NOT EXISTS t_attribute_set(
  attribute_set_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  attribute_set_name INT(11) NULL COMMENT '属性集名称'
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

#属性集-sku属性对应表
CREATE TABLE IF NOT EXISTS t_sku_attribute_and_attribute_set(
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  attribute_set_id INT(11) NOT NULL,
  sku_attribute_id INT(11) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

#属性集-属性对应表
CREATE TABLE IF NOT EXISTS t_attribute_and_attribute_set(
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  attribute_set_id INT(11) NOT NULL,
  attribute_id INT(11) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;


#分类
CREATE TABLE IF NOT EXISTS t_category(
  category_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  sup_category_id INT(11) DEFAULT -1 COMMENT '父分类id',
  categroy_name VARCHAR(255) NOT NULL COMMENT '分类名称',
  preview VARCHAR(255) NULL DEFAULT "无介绍" COMMENT '简介'
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

CREATE UNIQUE INDEX t_category_category_name_uindex ON t_category (categroy_name);

#品牌
CREATE TABLE IF NOT EXISTS t_brand(
  brand_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  brand_name VARCHAR(255) NOT NULL COMMENT '品牌名称',
  introduction TEXT NULL COMMENT '介绍',
  logo_url VARCHAR(255) NOT NULL COMMENT 'Logo的URL'
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
