CREATE DATABASE IF NOT EXISTS e_shop;

USE e_shop;

CREATE TABLE IF NOT EXISTS t_user(
  user_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(255) UNIQUE NOT NULL ,
  e_mail VARCHAR(255) NOT NULL ,
  password VARCHAR(255) NOT NULL ,
  phone VARCHAR(255) NULL,
  salt VARCHAR(255) NOT NULL,
  head_url VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL DEFAULT "ROLE_USER"
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_login_ticket(
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  expired TIMESTAMP,
  ticket VARCHAR(255)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;