CREATE DATABASE IF NOT EXISTS e_shop;

USE e_shop;

CREATE TABLE IF NOT EXISTS t_order(
  order_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  address_id INT(11) NOT NULL ,
  status VARCHAR(255) NOT NULL DEFAULT "未付款"
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_sku_and_order(
  sku_and_order_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  sku_id INT(11) NOT NULL ,
  order_id INT(11) NOT NULL ,
  sku_amount INT(11) NOT NULL DEFAULT 1
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
