eureka:
  client:
    service-url:
      #defaultZone: http://eureka.springcloud.cn/eureka/
      defaultZone: http://www.doperj.top:8761/eureka
server:
  port: 8080

spring:
  application:
    name: gateway

zuul:
  routes:
    product-services: /api/**
