eureka:
  client:
    service-url:
      #defaultZone: http://eureka.springcloud.cn/eureka/
      defaultZone: http://www.doperj.top:8761/eureka
server:
  port: 8080

spring:
  application:
    name: gateway

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    product-services: /gateway/**
    #order-services: /gateway/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
