eureka:
  client:
    service-url:
      #defaultZone: http://eureka.springcloud.cn/eureka/
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://www.doperj.top:8761/eureka
server:
  port: 8083

spring:
  redis:
    database: 0      # Redis数据库索引（默认为0）
    host: www.doperj.top # Redis服务器地址
    port: 6379       # Redis服务器连接端口
    password: 515300        # Redis服务器连接密码（默认为空）
    timeout: 10000       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0    # 连接池中的最小空闲连接
  application:
    name: order-services
  datasource:
    name: test
    url: jdbc:mysql://119.23.225.135:3306/e_shop?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 515300
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html

## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.doperj.order.domain
  configuration:
    map-underscore-to-camel-case: true


