spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    hostname: www.doperj.top
  client:
    fetch-registry: true
    register-with-eureka: false
  server:
    enable-self-preservation: true
